export const stack = [
  {
    category: "Frontend",
    icon: "devices",
    iconColor: "text-blue-500",
    bgColor: "bg-zinc-900/50",
    skills: [
      "HTML",
      "CSS",
      "Javascript",
      "TypeScript",
      "Tailwind CSS",
      "Bootstrap",
      "Shadcn",
      "Next.js",
      "React.js",
      "Zustand",
      "Axios",
    ],
  },
  {
    category: "Backend",
    icon: "dns",
    iconColor: "text-green-500",
    bgColor: "bg-zinc-900/80",
    skills: [
      "Node.js",
      "Express.js",
      "Go",
      "Prisma ORM",
      "PostgreSQL",
      "My SQL",
      "MongoDB",
      "Rest API",
      "Supabase",
    ],
  },
  {
    category: "Integrations & Tools",
    icon: "bolt",
    iconColor: "text-purple-500",
    bgColor: "bg-zinc-900/50",
    skills: [
      "Gemini AI API",
      "Midtrans Payment",
      "Redis",
      "Cloudinary",
      "Vercel",
      "Git / GitHub",
      "Postman",
      "Figma",
      "VS Code",
    ],
  },
];
